"""Planning schemas with strict structure to support future tool-calling LLM integration."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class Goal(BaseModel):
    """User or system goal describing desired StoneBlock 4 progression outcome."""

    goal_id: str = Field(..., min_length=1)
    description: str = Field(..., min_length=3)
    priority: int = Field(default=1, ge=1, le=10)


class Action(BaseModel):
    """Deterministic low-level command sent to the bridge; never delegated to per-tick LLM control."""

    action_type: Literal[
        "noop",
        "select_hotbar_slot",
        "turn_to_yaw_pitch",
        "move_forward_short",
        "interact_use",
        "inventory_click",
        "mine_block",
        "place_block",
    ]
    parameters: dict[str, str | int | float | bool] = Field(default_factory=dict)
    timeout_ticks: int = Field(default=120, ge=1)


class Subtask(BaseModel):
    """Intermediate unit of work in a plan, typically mapping to a coherent StoneBlock activity segment."""

    subtask_id: str = Field(..., min_length=1)
    title: str = Field(..., min_length=3)
    success_criteria: list[str] = Field(..., min_length=1)
    actions: list[Action] = Field(..., min_length=1)


class Plan(BaseModel):
    """Hierarchical plan generated by planner layer and consumed by executor layer."""

    plan_id: str = Field(..., min_length=1)
    goal: Goal
    subtasks: list[Subtask] = Field(..., min_length=1)
    rationale: str = Field(..., min_length=5)

    @field_validator("subtasks")
    @classmethod
    def unique_subtask_ids(cls, subtasks: list[Subtask]) -> list[Subtask]:
        ids = [subtask.subtask_id for subtask in subtasks]
        if len(ids) != len(set(ids)):
            raise ValueError("subtask_id values must be unique within a plan")
        return subtasks
